# Generated by Django 3.0.8 on 2020-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhstore', '0003_auto_20200802_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Opłacone', 'Opłacone'), ('Do wysyłki', 'Do wysyłki'), ('Dostarczone', 'Dostarczone')], max_length=100, null=True),
        ),
    ]
