# Generated by Django 3.0.8 on 2020-08-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhapipage', '0003_auto_20200811_0819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeForm',
        ),
    ]
