# Generated by Django 3.0.8 on 2020-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhblog', '0004_auto_20200813_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='snippet', max_length=100),
        ),
    ]
