# Generated by Django 3.0.8 on 2020-08-15 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fhblog', '0009_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/fhblog'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/fhblog/profiles'),
        ),
    ]
